apiVersion: v1
kind: Service
metadata:
  name: pyspark-matrix-service
spec:
  type: LoadBalancer
  selector:
    app: pyspark-matrix
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
